### ISSUE TITLE
how to generate "tag" and "archive" page

### ISSUE THREAD

**Issue by renehiroki** [wlh320/hugo-theme-hulga#1]
Hi, I'm newbie about r package "blogdown" and Hugo web site generator.

I'm very exited about this hulga layout.

Though, I can't understand how to get tag page and archive page.
Could you teach me that?

thanks.

**Comment by wlh320** [comment]
Hi, I'm glad you like this theme. Thanks!

1. the tag page and category page are generated automatically as long as you add tag or category in one post's front matter.
Hugo document about front matter: https://gohugo.io/content-management/front-matter/

2. You can generate an archive page by using this command `hugo new archives/index.md` just like creating a new post.
After that the archive page will be at http://your.site/archives/ every time you generate the whole site.

**Comment by renehiroki** [comment]
I see, completely understand. thanks!

https://renehiroki.rbind.io/

**Comment by tao-bioinfo** [comment]
@wlh320 It is better to add this to README

**Comment by wlh320** [comment]
> @wlh320 It is better to add this to README

Thank you, I'll update README if I have time.
