### ISSUE TITLE
catagories and tags are overlapping in mobile view

### ISSUE THREAD

**Issue by itsNik** [wlh320/hugo-theme-hulga#2]
Tags are overlapping with the categories in mobile view:
![hugla](https://user-images.githubusercontent.com/11682776/128609834-2001eaf4-3fd4-471d-912f-8762421605f2.JPG)

Unfortunately I wasn't able to find a proper solution by myself. Maybe someone else can help.

**Comment by wlh320** [comment]
Hi, thanks for your reply.
One easy solution is removing the `post-box-tags` class in [this line](https://github.com/wlh320/hugo-theme-hulga/blob/539caeec7c7dc5fac4fb0ff872e639262b495f69/layouts/partials/posts.html#L13) and after that tags will not overlap, but they will appear at top-left instead of bottom-right. 

I'm not good at web frontend development especically writing CSS myself. I'll try to figure out a more reasonable solution to show bottom-right tags without overlapping in a narrow box.

**Comment by itsNik** [comment]
Hey, thanks for your fast reply.
I kinda achived the same with removing [this line](https://github.com/wlh320/hugo-theme-hulga/blob/539caeec7c7dc5fac4fb0ff872e639262b495f69/assets/css/common.scss#L115) in the **common.scss** file.
But my attempt has the exact same problem, the tags appear at top-left.

Would be great if we could figure something out. In my opionion the tags above the headline don't look that good nor do they fit the whole theme.

**Comment by wlh320** [comment]
I think I've solved it by using flex in [this commit](https://github.com/wlh320/hugo-theme-hulga/commit/43cd8c06d462566bf460e2701b34f9a9396517b6).

**Comment by itsNik** [comment]
Thank you @wlh320, it works as expected.
I also moved the "tags div" in **term.html**  so that its displayed correctly for categories and tags.

```html
{{ define "main" }}
{{- partial "header.html" . -}}
{{- $ctx := . -}}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-2"></div>
      <div class="column is-8">
        {{ if eq .Data.Singular "category" }}
        <nav class="breadcrumb is-centered is-medium" aria-label="breadcrumbs">
          <ul>
            <li><a href={{"categories" | absURL}}>{{- i18n "categories" -}}</a></li>
            <li class="is-active"><a href="#">{{ .Data.Term }}</a></li>
          </ul>
        </nav>
        {{ else if eq .Data.Singular "tag" }}
        <nav class="breadcrumb is-centered is-medium" aria-label="breadcrumbs">
          <ul>
            <li><a href="{{"tags" | absURL }}">{{- i18n "tags" -}}</a></li>
            <li class="is-active"><a href="#">{{ .Data.Term }}</a></li>
          </ul>
        </nav>
        {{ end }}
        <div class="post-lists">
          {{ $paginator := .Paginate (where .Data.Pages "Type" "post") }}
          {{ range $paginator.Pages }}
              <div class="box post-box">
                
                <div class="post-box-title">
                  <a href="{{.Permalink }}" class="title is-size-5">{{ .Title }}</a>
                </div>
                <div class="post-box-meta">
                  {{ .Date.Format "2006/01/02" }}
                  {{ with .Params.Categories }} ・
                  {{ range .}}
                  <span class="post-tag post-box-category">
                    <a href="{{ $ctx.Site.BaseURL }}{{ "/categories/" | relLangURL }}{{ . | urlize }}">{{ . }}</a>
                  </span>
                  {{ end }}
                  {{ end }}
                </div>
                {{ with .Params.Tags }}
                <div class="post-box-tags">
                  {{ range .}}
                  <span class="post-tag post-box-tag">
                    <a href="{{ $ctx.Site.BaseURL }}{{ "/tags/" | relLangURL }}{{ . | urlize }}">#{{ . }}</a>
                  </span>
                  {{ end }}
                </div>
                {{ end }}
              </div>
          {{ end }}
          {{ partial "paginator.html" . }}
        </div>
      </div>
      <div class="column is-2"></div>
    </div>
  </div>
</section>
{{ end }}
```

**Comment by wlh320** [comment]
Thank you! After I commented last week I realized that I forgot the taxonomy pages and I've fixed it in [this comment](https://github.com/wlh320/hugo-theme-hulga/commit/39192947cc5f06e030c7e9c0f19d9531b509bd5f) in the next day. Hope you like this theme!
