### ISSUE TITLE
absolute internal links vs relative internal links

### ISSUE THREAD

**Issue by oupala** [wlh320/hugo-theme-hulga#4]
It looks like the layout is using absolute internal links while it would be more resilient to use relative internal links.

```
<a href="{{ $ctx.Site.BaseURL }}{{ "/tags/" | relLangURL }}{{ . | urlize}}/">#{{ . }}</a>
```

could be replaced by

```
<a href="{{ "/tags/" | relLangURL }}{{ . | urlize}}/">#{{ . }}</a>
```

This make the theme easy to use even on a local development or local edition.

**Comment by wlh320** [comment]
Thank you! It's a good advice. I will fix that.

**Comment by oupala** [comment]
Great, thank you!
