### ISSUE TITLE
Modify favicon for Hulga theme

### ISSUE THREAD

**Issue by KylieWang-QY** [wlh320/hugo-theme-hulga#7]
Do you know the steps for modifying the favicon for Hulga theme?

**Comment by wlh320** [comment]
You can just put your favicon file into the `static` folder of your hugo site.

**Comment by KylieWang-QY** [comment]
Could you please confirm whether the `static` folder under the hugo site folder should be used for the favicon file instead of the `themes/hulga/static`?  Why is the default favicon still present when we run `hugo server` for prereview?

**Comment by wlh320** [comment]
This theme doesn't have its own favicon. I just created a new hugo site and tested, I think `static` folder under the hugo site is ok, you don't need to change themes folder. If you change a favicon of your site, maybe you should clear the cache and refresh (Ctrl + F5)?

**Comment by KylieWang-QY** [comment]
Thanks whl320, I solved the issue by following steps:

- Add `<link href="/img/favicon.ico" rel="icon"> ` on the `/hugosite/themes/hulga/layouts/partials/head.html`
- Copy the `favicon.ico` into `hugosite/static/img`
- Add `favicon = "/img/favicon.ico"` on `/hugosite/config.toml`
