### ISSUE TITLE
Blog article's words size on the Homepage

### ISSUE THREAD

**Issue by KylieWang-QY** [wlh320/hugo-theme-hulga#8]
Hi, I have noticed that on Hulga's demo site and zilcH40's Blog, blog articles only display the first sentence on the home page, followed by "Read more". 

But articles on my homepage show 6-7 lines each, although it still stops at the period (".") before "read more", but it includes multiple sentences (4 sentences).

Do you know how to config this to improve the reading experience?

**Comment by wlh320** [comment]
In hugo, you can set the length of summary as [Docs](https://gohugo.io/content-management/summaries/#automatic-summary-splitting) says. 

Another potential reason is that you are using CJK languages, for your reference:

>The Hugo-defined summaries are set to use word count calculated by splitting the text by one or more consecutive whitespace characters. If you are creating content in a CJK language and want to use Hugo’s automatic summary splitting, set hasCJKLanguage to true in your [site configuration](https://gohugo.io/getting-started/configuration/).

**Comment by KylieWang-QY** [comment]
Thanks! I added `summaryLength = 30` in the config.toml to solve the issue. it can also manually split the summary by adding `<!--more-->`, but using `<!--more-->` , the "Read more" will display in a newline
