### ISSUE TITLE
Capitalisation issues with tags and categories in Hugo/hulga

### ISSUE THREAD

**Issue by KylieWang-QY** [wlh320/hugo-theme-hulga#9]
Hi!  I noticed that the default tags and archives are all replaced with lowercase, which is not perfect in the case of "IaC", "CICD", etc.

I added `disablePathToLower = true` and `preserveTaxonomyNames = true` in the config.toml, which partially solved the problem. 
- On the left side of the homepage, the tags and categories of the article part (at the bottom of the article summary) can be reserved in uppercase.
- Click on any article, the categories on the second line, and the tags on the third line can also be capitalized

However,
- On the right side of the homepage, categories and tags are all replaced with lowercase words
- After clicking on the tags and categories buttons in the upper right corner, they are all replaced with lowercase

May I ask how to keep uppercase in tags and categories?

**Comment by wlh320** [comment]
Thank you. I tested on my own site, and I found if I enable both of those two configs, this problem will not arise. If I set `preserveTaxonomyNames = true` only, I encountered a situation similar to yours. Maybe it is because I use a wrong function in hugo? I'll investigate it further.

**Comment by wlh320** [comment]
I found that I list categories/tags in a strange way in my code, maybe I should read hugo's documents again to learn how to do it in a normal way.  I'll rewrite taxonomy part of this theme in my part time, it may takes several days.

**Comment by wlh320** [comment]
You can check the latest commit, I think it should show the correct name of categories/tags without additional configs now.

**Comment by KylieWang-QY** [comment]
Great! Solved the issue.

Thanks wlh320!
